name: Lint

on:
  push:
    paths:
      - "**.js"
      - ".eslint*"
      - ".github/workflow/lint.yml"
  pull_request:
    paths:
      - "**.js"
      - ".eslint*"
      - ".github/workflow/lint.yml"
  
jobs:
  test:
    name: Lint with ESLint
    runs-on: ubuntu-latest
    env:
      node-version: 20
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      
      - name: Environment Information
        run: |
          node --version
          npm --version
      
      - name: Run npm install
        run: |
          npm ci
      
      - name: Lint code
        run: |
          npm run lint
    
    